name: jetcventerprise
description: "JetCV Enterprise - Supabase Integration App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.3.4
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^16.2.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # Forms & Validation
  form_builder_validators: ^11.2.0
  flutter_form_builder: ^10.2.0
  
  # Authentication
  google_sign_in: ^7.1.1
  
  # HTTP & API
  dio: ^5.4.0
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.20.2
  url_launcher: ^6.2.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Permissions
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/config/
